# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simplecli < Formula
  desc "A simple CLI tool to explain automated deployments"
  homepage "https://github.com/marianina8"
  version "1.0.2-beta"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/marianina8/simplecli/releases/download/1.0.2-beta/simplecli_Darwin_x86_64.tar.gz"
      sha256 "990af8ec2d3f8700c1126393bc4fd842b837e73c8615150ebaae77996e5f445d"

      def install
        bin.install "simplecli"
      end
    end
    on_arm do
      url "https://github.com/marianina8/simplecli/releases/download/1.0.2-beta/simplecli_Darwin_arm64.tar.gz"
      sha256 "69b04fc997bae10e67686fb8f8ce26e21b49e552bc3f72260ddbc7ded435af89"

      def install
        bin.install "simplecli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/simplecli/releases/download/1.0.2-beta/simplecli_Linux_x86_64.tar.gz"
        sha256 "9dfaf25234d17622d3c69257cafae04d3c82a8f7b7f8102442c60ad9319cff2a"

        def install
          bin.install "simplecli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/simplecli/releases/download/1.0.2-beta/simplecli_Linux_arm64.tar.gz"
        sha256 "4901def588f1e9ec422a3f4febc28eb857de8d079fcf80e9aa56a1abde5375da"

        def install
          bin.install "simplecli"
        end
      end
    end
  end
end
