# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simplecli < Formula
  desc "A simple CLI tool to explain automated deployments"
  homepage "https://github.com/marianina8"
  version "1.0.4-beta"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/marianina8/simplecli/releases/download/1.0.4-beta/simplecli_Darwin_x86_64.tar.gz"
      sha256 "48c2e262d505e20508d338f5f7507cee594645e9bf90ea613d8ebbeba0883bfd"

      def install
        bin.install "simplecli"
      end
    end
    on_arm do
      url "https://github.com/marianina8/simplecli/releases/download/1.0.4-beta/simplecli_Darwin_arm64.tar.gz"
      sha256 "c7f19d55a626b00ac62729a3f8c4948f670eda9398ecfd361322da3e83cd532b"

      def install
        bin.install "simplecli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/simplecli/releases/download/1.0.4-beta/simplecli_Linux_x86_64.tar.gz"
        sha256 "7e096befb08e515b4586e91b45ee9ac26326b60bdebbf17f8a033c9a6e940ec3"

        def install
          bin.install "simplecli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marianina8/simplecli/releases/download/1.0.4-beta/simplecli_Linux_arm64.tar.gz"
        sha256 "7d187d4bec17d48be16a822d6513edc53b3462b6b98b50b3cbde0ee6de22689a"

        def install
          bin.install "simplecli"
        end
      end
    end
  end
end
